# Generated by Django 3.2.4 on 2021-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pointGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', models.CharField(max_length=100)),
                ('shot_date', models.DateTimeField(verbose_name='photo date')),
                ('clean_state', models.BooleanField(default=False)),
            ],
        ),
    ]
